### ISSUE TITLE
runtime dispatch and other goodies from upstream

### ISSUE THREAD

**Issue by sunnygleason** [simd-lite/simd-json#104]
One idea we should consider soonish is compiling everything for the target architecture regardless of CPU features and doing runtime detection & dispatch (as implemented in upstream, hopefully easier in Rust?).

There might be other goodies in upstream as well...

**Comment by Licenser** [comment]
I got no idea how that'd work in rust but that just means we got to learn something new :D

**Comment by CJP10** [comment]
I’ll have a go at this. @Licenser can you assign this to me 😄 .

**Comment by Licenser** [comment]
Thanks @CJP10 go for it :)

**Comment by AndreKR** [comment]
> I got no idea how that'd work in rust but that just means we got to learn something new :D

From what I understand you use something like `is_x86_feature_detected!("ssse3")` to detect whether a particular feature is available. Then you call a function optimized for that feature. You have to mark the function with `#[target_feature(enable = "ssse3")]` to force usage of that feature within the function.

[Here an example](https://github.com/BurntSushi/aho-corasick/blob/933b6a71aedc6d2a3c399f250a2ff30479407328/src/packed/teddy/compile.rs#L89-L90) and [another one](https://github.com/BurntSushi/rust-memchr/blob/378bb1caecac7079b867fa6e6059c0d8ea244e03/src/x86/mod.rs#L9-L60).

**Comment by CJP10** [comment]
@AndreKR upstream does something similar to `ifunc`.

**Comment by Licenser** [comment]
Ja, we probably want something resembling the upstream solution that does only once include a conditional and after that memorizes the choice.

**Comment by CJP10** [comment]
To add, we should also have a `simd_json::init()`. Which would be optional but perform the runtime selection.

**Comment by Licenser** [comment]
Yes very good idea 👍 that way applications who want to make sure there is 0 overhead on the hot path can call it on startup :), good thinking!

**Comment by Count-Count** [comment]
Maybe take some inspiration from rust-memchr: [ifunc-like macro for Rust](https://github.com/BurntSushi/rust-memchr/blob/d6b81866920615a75e1e53f880050e1e8d3f565a/src/x86/mod.rs#L31)
