### ISSUE TITLE
Serializer and Deserialize derives

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simd-json#121]
It might be worth looking into making more performant versions of the serialize and deserialize macro. Serde's implementation factors in different formats and by that comes with different tradeoffs if we focus on JSON it is likely that we can be significantly faster matching at least DOM object serialization speeds and improving deserialization speed further.

**Comment by pickfire** [comment]
I am wondering why doesn't `struct` outperform `DOM` since the details is available upfront and the compiler is able to optimize the code based on how it was structured, maybe because of the number of allocations needed?

**Comment by Licenser** [comment]
The Derive's serde have are generic over different formats, that greatly reduces the number of optimizations you can do and increases the number of indirection's required. 

As a simple example field names in serde have to be escaped for every invocation since different encoders will need different encoding rules. A JSON specific serialisercan cache those names and reduce the needed interaction to a simple memcopy of `"<encoded-field-name>":` instead of having 4 writes and a encoding step

**Comment by Licenser** [comment]
Some first results on a serializer:
![image](https://user-images.githubusercontent.com/119093/79388273-54daa700-7f6d-11ea-9234-f16b6415823e.png)

**Comment by Licenser** [comment]
there is now simd-json-derive
