### ISSUE TITLE
An equivalent to serde_json's Deserializer

### ISSUE THREAD

**Issue by vivianhellyer** [simd-lite/simd-json#139]
A library that I'm working on supports toggling between using serde_json and simd-json internally, and I've run into the need for deserializing something via a `DeserializeSeed` deserializer. To do this I've used [`serde_json::Deserializer`](https://docs.rs/serde_json/1.0.56/serde_json/struct.Deserializer.html), but I can't see an equivalent way to do this with simd-json. Here's what the use case looks like:

```rust
use serde::DeserializeSeed;
use serde_json::Deserializer;

let seeded_deserializer = SomeSeededDeserializer(seed);
let mut json_deserializer = Deserializer::from_str(json_payload);

let deserialized_value = seeded_deserializer.deserialize(&mut json_deserializer)?;
```

Is this something feasible with the library's design? I'm not too familiar with it. I see a private `Deserializer` in the crate root which looks like it might fit this need.

**Comment by Licenser** [comment]
Hi!
Puh, that's a tough question, I never heard of Seeded Deserializer until today so my answers might be a bit incorrect (sorry). 

Generally, yes you are right simd_json tries to be compatible, so you should be able to use the `Deserializer` (https://github.com/simd-lite/simd-json/blob/main/src/lib.rs#L400) and use DeserializeSeed from serde as well. That said it's not public at the moment, I'll update that later today.

Alternatively (and a lot more work) would be going over the token stream yourself (that'll be faster than using serde interop) but more work -https://github.com/simd-lite/simd-json/blob/main/src/value/owned.rs#L282-L326 is an example.

**Comment by Licenser** [comment]
published as `v0.3.10`, hopes this makes it easier to use :)! 

Slightly unrelated I'd be super eager to hear any feedback on the ergonomics of simd-json and what people like /dislike.

I know the one big ick is that the input is mutable but other then that I'd had very little feedback.

**Comment by vivianhellyer** [comment]
After a first pass it looks like it works great, thanks! I haven't used simd-json before so I don't have a lot of feedback right now. For this use case I do some scanning of the payload and seed parts of the deserialiser with references to small portions of the payload for more efficient deserialisation of an inner enum object, but like you said due to the mutable requirement making that tricky I'll have to change that around. When I have feedback I'll let you know!

Thanks for the quick publish! :)

**Comment by Licenser** [comment]
Thank you! :D
