### ISSUE TITLE
missing suppor to deser array to struct

### ISSUE THREAD

**Issue by serzhiio** [simd-lite/simd-json#148]
hi, i'm switching to **simd_json** from **serde_json** and started to receive this error: `Error { index: 0, character: '?', error: ExpectedMap }'`.
What could it be?

**Comment by serzhiio** [comment]
```
let p = simd_json::from_slice(unsafe{raw.as_bytes_mut()}).unwrap();
let parsed: OrderBook = simd_json::serde::from_owned_value(p).expect("Bad raw data!"); // error here
```

**Comment by Licenser** [comment]
Heya two fold answer:

1) That looks like a bug in the DOM->object translation but to fix it I'd need to know the type definition of OrderBook and an example entry to deserialise (structure is more relevant then content) 

2nd

You might not need that at all, the code does an extra step that will make it probably slower then using serde directly.

What happens is there are two translations:

Raw -> DOM
DOM -> Struct

```rust
let p = simd_json::from_slice(unsafe{raw.as_bytes_mut()}).unwrap();
let parsed: OrderBook = simd_json::serde::from_owned_value(p).expect("Bad raw data!"); // error here
```

can be rewritten as:
```rust
let parsed: OrderBook = simd_json::serde::from_slice(unsafe{raw.as_bytes_mut()}).expect("Bad raw data!"); // error here
```

Which should bypass the issue and be faster.

Alternatively if you're up for a bit of an adventure there is https://docs.rs/simd-json-derive/0.1.11/simd_json_derive/ which is a simd-json native derive. It is still quite experimental and doesn't cover nearly as much ground as serde-derive, but when it works ti works significantly fast. So if you derive `simd_json_derive::Deserialize` for order book (and it doesn't blow up in your face) you could write:
```rust
let parsed = OrderBook::from_slice(unsafe{raw.as_bytes_mut()}).expect("Bad raw data!"); // error here
```

**Comment by serzhiio** [comment]
Deser structs:
```
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct OrderBook {
    pub last_update_id: u64,
    #[serde(rename = "E")]
    pub event_time: Option<u64>, // only futures
    #[serde(rename = "T")]
    pub transaction_time: Option<u64>, // only futures
    pub bids: Vec<Bid>,
    pub asks: Vec<Ask>,
}
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Bid {
    #[serde(with = "string_or_float")]
    pub price: f64,
    #[serde(with = "string_or_float")]
    pub qty: f64,
}
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Ask {
    #[serde(with = "string_or_float")]
    pub price: f64,
    #[serde(with = "string_or_float")]
    pub qty: f64,
}
```
Incoming data:
```
{
  "lastUpdateId": 1027024,
  "E": 1589436922972,   // Message output time
  "T": 1589436922959,   // Transaction time
  "bids": [
    [
      "4.00000000",     // PRICE
      "431.00000000"    // QTY
    ]
  ],
  "asks": [
    [
      "4.00000200",
      "12.00000000"
    ]
  ]
}
```

**Comment by Licenser** [comment]
I think I know the issue :) I didn't have an example where a array gets serialized into a struct.

I think 

```json
 [
      "4.00000000",     // PRICE
      "431.00000000"    // QTY
    ]
```

to 

```rust
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Bid {
    #[serde(with = "string_or_float")]
    pub price: f64,
    #[serde(with = "string_or_float")]
    pub qty: f64,
}
```

is where the issue is :) I'll add a test for that but I'm a bit bussy or you can throw one in an try to fix it ;)

**Comment by Licenser** [comment]
Fixed the decoding issue, for performance reasoins I still recommand this version:

```rust
let parsed: OrderBook = simd_json::serde::from_slice(unsafe{raw.as_bytes_mut()}).expect("Bad raw data!");
```
