### ISSUE TITLE
Reuse allocations in hot paths

### ISSUE THREAD

**Issue by CJP10** [simd-lite/simd-json#156]
There are tons of big allocations in the hot path, some in stage 1 and most in stage 2. I think we should go through and try to make these reusable at the very least. Ideally we use some custom allocators, `bumpalo` being a good fit for stage2 parsing. In general, the idea is to make use of the `Deserializer` struct and have it own a majority of the big allocations / custom allocators. Instead of creating a `Deserializer` for each deserialization, you would use the `Deserializer` multiple times.

**Comment by Licenser** [comment]
That's a really good observation 👍

**Comment by CJP10** [comment]
@Licenser go ahead and assign this to me 😄

**Comment by Licenser** [comment]
Yay!

**Comment by Licenser** [comment]
CJP contributed a patch to this closing it
