### ISSUE TITLE
Using integer as a map key causes incorrect rendering

### ISSUE THREAD

**Issue by Kogia-sima** [simd-lite/simd-json#167]
## Description

I'd like to serialize BTreeMap which has integer as a key. However, when I passed map into `to_string` or `to_string_pretty`, `simd_json` outpus invalid JSON data.

```rust
use std::collections::BTreeMap;

fn main() {
    let mut map = BTreeMap::new();
    map.insert(0, "foo");
    map.insert(1, "bar");
    map.insert(2, "baz");

    println!("{}", simd_json::to_string_pretty(&map).unwrap());
}
```

output:

```
{
  0: "foo",
  1: "bar",
  2: "baz"
}
```

## Expected behavior

I want the JSON output like this:

```json
{
  "0": "foo",
  "1": "bar",
  "2": "baz"
}
```

## Possible solution

`serde_json` crate defines a new struct named [`MapKeySerializer`](https://github.com/serde-rs/json/blob/8d78020522b4d3001be5f9c613bf4b5a6e63618a/src/ser.rs#L841-L1194) to properly render the map keys.

## Environment

|Software|Version|
|--|--|
|OS|Lubuntu 20.04.2 LTS|
|rustc|rustc stable 1.48.0 (7eac88abb 2020-11-16)|
|simd-json|0.3.23|

**Comment by Licenser** [comment]
This is fixed
