### ISSUE TITLE
Parsing U64(X) as f64 shows zero instead of number.

### ISSUE THREAD

**Issue by serzhiio** [simd-lite/simd-json#185]
I'm trying to parse U64(X) value with `.as_f64()` function.
Result is zero instead of real number.
Feels like behavior should be trivial like using `as f64` on integers.

**Comment by serzhiio** [comment]
Hah... just discovered `.cast_f64()`.

**Comment by Licenser** [comment]
:D

Ja to explain the history and reasoning, all `as_` functions require lossless conversion i.e. calling `as_u8` in a `u64` will only return Some(u8) if the value is, in fact, representable as a u8.

the `cast_` indicates a potentially lossiness as it type casts :)

I hope that makes sense!

**Comment by jon-chuang** [comment]
Why can't we implement as_f64 on U64 as u64.try_into::<f64> instead? 

cast_ is lossy, but try_into is lossless and returns None when lossy. I think this is the desired behaviour as one never wants a lossy conversion when parsing a json, and forbidding parsing 123 `as_f64` is too restrictive.
