### ISSUE TITLE
can't compile on an Intel i7 10700K

### ISSUE THREAD

**Issue by whyCPPgofast** [simd-lite/simd-json#197]
Hi, my CPU is AVX2 capable.
Here is my cargo.toml
I tried running without allow-non-simd but the error is the same.

rustc 1.48.0
I'm on windows 10 if that matters
```
[dependencies]
simd-json = { version = "0.4.5", features = ["allow-non-simd"] }

[build]
rustflags = ["-C", "target-cpu=native"]
```
Error:
```
error[E0277]: the trait bound `<Self as ValueAccess>::Target: Value` is not satisfied
   --> C:\Users\Edi\.cargo\registry\src\github.com-1ecc6299db9ec823\value-trait-0.2.4\src\lib.rs:164:17
    |
164 |     type Array: Array<Element = Self::Target>;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Value` is not implemented for `<Self as ValueAccess>::Target`
    | 
   ::: C:\Users\Edi\.cargo\registry\src\github.com-1ecc6299db9ec823\value-trait-0.2.4\src\array.rs:6:11
    |
6   | pub trait Array: Index<usize> + Sync + Send + Clone {
    |           ----- required by a bound in this
7   |     /// Elements of the array
8   |     type Element: Value;
    |                   ----- required by this bound in `Array`
    |
help: consider further restricting the associated type
    |
188 |         Q: Hash + Eq + Ord, <Self as ValueAccess>::Target: Value
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
theres about 10 of these very similar error messages

**Comment by Licenser** [comment]
That's quite odd, can you share the code around this so I can try to replicate it locally?

**Comment by whyCPPgofast** [comment]
this is an isolated project to try this library.

```
use simd_json;

fn main() {
    let mut d = br#"{"some": ["key", "value", 2]}"#.to_vec();
    let v: simd_json::OwnedValue = simd_json::to_owned_value(&mut d).unwrap();
    println!("{:?}", v);
}
```

**Comment by Licenser** [comment]
Oh that's a good call, you are right the minimal rust version needed is 1.49, you could go with 0.3 if simd-json that should support older versions or ideally update reust :)

**Comment by whyCPPgofast** [comment]
glad that its a simple problem. upgraded my rustc and now it works thanks! I was going through docs.rs and readme but didn't see any mentions of minimal rustc my bad.

**Comment by Licenser** [comment]
Nah it's not listed anywhere, that's on me :) and sadly the RFC for adding the MRV to the Cargo.tolm isn't done yet :(

**Comment by Licenser** [comment]
I've adfded the MRV to the cargo, that way, once the RFC makes it it'll get automatically picked up
