### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simd-json#217]
Whilst WASM doesn't expose the native CPU instructions, it does have its own SIMD intrinsics (see https://doc.rust-lang.org/core/arch/wasm32/index.html#simd).

I had a quick look at porting this crate to WASM this evening and it seems to be feasible. I've not had a chance to test it in the slightest, but it builds. (https://github.com/sam-kirby/simd-json/tree/wasm)

I'll try including it in a yew project I'm working on tomorrow and see if it a) works and b) offers any performance improvements.

_Originally posted by @sam-kirby in https://github.com/simd-lite/simd-json/issues/161#issuecomment-1043640140_

**Comment by Licenser** [comment]
@Sparkenstein  this might be of interest to you :)

**Comment by Sparkenstein** [comment]
thank you so much, this helps a lot 👍
