### ISSUE TITLE
Unsoundness in stage2 deserializer

### ISSUE THREAD

**Issue by Nilstrieb** [simd-lite/simd-json#226]
Here, two `Vec`s are created and then the `len` is immediately set, and later `get_unchecked_mut` is used to set the items. This is unsound, as the docs for [`Vec::set_len`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.set_len) mention.
 
> `The elements at old_len..new_len must be initialized.`

`get_unchecked_mut` later also creates a `&mut T` to uninitialized memory, which is not sound either.

https://github.com/simd-lite/simd-json/blob/d426844e2d7f403bfe4bb576fee0e604141378aa/src/stage2.rs#L125-L135

The correct solution would be to use `vec.as_mut_ptr().add(idx).write(value)` to set the items, and only use `set_len` in the end when everything has been initialized.

**Comment by Nilstrieb** [comment]
Thank you for the quick response!

**Comment by Licenser** [comment]
Thank you for bringing it up :) was a good insight!
