### ISSUE TITLE
how unsafe is unsafe?

### ISSUE THREAD

**Issue by nonetrix** [simd-lite/simd-json#234]
I am aware that this code uses unsafe often, but how unsafe is it? How likely is the unsafe code to be vulnerable in any meaningful way? 

I'm sorry if this has already been asked but I searched the issues and could not find such a thing

**Comment by nonetrix** [comment]
Also, as a suggestion maybe an option in cargo.toml could remove unsafe blocks. Downside being lesser performance since judging by the read me it's possible to do safely just slower

**Comment by nonetrix** [comment]
Thanks for clarifying

**Comment by Licenser** [comment]
Glad it helped :)
