### ISSUE TITLE
mismatched return types while building

### ISSUE THREAD

**Issue by ShashankKumarSaxena** [simd-lite/simd-json#239]
Whenever I build my project which uses `simd-json` Version `0.6.0`, it throws an error saying `expected '!', found '()'`
![image](https://user-images.githubusercontent.com/69804741/178537566-cef645e5-0555-484d-bed7-a8af55aaef6e.png)

My cargo version - 1.62.0

**Comment by mfelsche** [comment]
This is the not-so-obvious way of simd-json to tell you that you need to compile this on a CPU and with the right flags so has support for any of the supported platforms. One way is to use the rust-flag `-C target-cpu=native` if you are compiling for use on your machine where you compile. Another way is to explicitly list the features, e.g: `-C target-feature=+avx,+avx2,+sse4.2`.

**Comment by Licenser** [comment]
I'll close this as it seems to be resolved with Matthias answer
