### ISSUE TITLE
`from_str` should be unsafe

### ISSUE THREAD

**Issue by vilgotf** [simd-lite/simd-json#240]
`from_str` is documented as rewriting the `str`'s underlying slice in a way that it might no longer be a valid `str`. This, however, breaks the guarantees of `str` (that they are ALWAYS valid UTF-8). See `str::as_bytes_mut` for a similar method.

**Comment by Licenser** [comment]
That's a good point! Totally open to that change, do you want to make a PR to add an unsafe to from_str or should I just update it?

**Comment by dtolnay** [comment]
What is the correctness condition for a caller to use this function correctly? "Do not pass in non-ascii input whatsoever"?

"Do not pass in input that simd-json's present implementation would transform into non-utf8" is not really something that a caller can uphold.

**Comment by Licenser** [comment]
The input is treated as a `&mut [u8]` not a `&str` when replacing json utf8-escape sequences with their corresponding bytecode representation and shortening strings by that there is a chance that the resulting output isn't valid UTF8 any more.  So the "safe" way to use the function is treating the input as a u8 slice after calling it.

**Comment by vilgotf** [comment]
> That's a good point! Totally open to that change, do you want to make a PR to add an unsafe to from_str or should I just update it?

I'm guessing that this will cause downstream changes to other methods, with corresponding safety contracts to uphold. As I'm not familiar with this crate I'd rather you do it.
