### ISSUE TITLE
Implement Eq on owned::Value

### ISSUE THREAD

**Issue by kangalio** [simd-lite/simd-json#248]
It implements PartialEq, and as far as I can tell, it's possible to implement Eq too. This would be good to allow downstream users to implement Eq on their types.

**Comment by Licenser** [comment]
Eq can't safely be implemented on Value because it contains floats that do not provide an Eq implementation. Some of the details can be found tine [PartialEq](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html) documentation

**Comment by kangalioo** [comment]
In JSON, floats are finite. That's also why serde_json chooses to [implement Eq](https://github.com/serde-rs/json/blob/94019a31c6036dc4ebb9afc44a214f950caf0d1f/src/number.rs#L48) ([GitHub issue](https://github.com/serde-rs/json/issues/638))

**Comment by kangalioo** [comment]
Was it a deliberate decision to support non-finite floats in simd-json?

**Comment by Licenser** [comment]
It's a tradeoff, yes.

As @dtolnay points out, `serde_json` can avoid the `nan`/`inf` situation by having a custom, nested number type that prevents the creation of `nan`/`inf`.

This comes at the cost of loosing the ability to match against numbers and a deeper nested type structure, and a harder time interoperating with native rust number types.

With the simd-json API we decided to go a different direction, allowing easier matching and interoperability with numbers at the cost of having to deal with `nan` / `inf`.
