### ISSUE TITLE
Is this still based on upstream simdjson v0.2?

### ISSUE THREAD

**Issue by yay** [simd-lite/simd-json#249]
Is this still based on upstream simdjson v0.2?

Their version history only goes back to v0.3:
https://github.com/simdjson/simdjson/releases?page=4

What are the differences between this and the current version (2.x) of upstream simdjson, roughly?

**Comment by Licenser** [comment]
Heya,

sorry for the late reply, I was very busy vacationing and not looking at computers :D.

Yes we're still based on 0.2, not really because of a decision but mostly because neither I nor any one else has found the time to look at the delta between 0.2 and 0.3 and translate it as needed :(

**Comment by yay** [comment]
No worries. Sounds like you had a good time :) Thank you for your response.

**Comment by Licenser** [comment]
Thanks, I did, it was really refreshing. a 3.x update is on the (neve ending) todo list :D so it's not a decision against 0.3 just a time thing.

**Comment by Licenser** [comment]
superseded by #349
