### ISSUE TITLE
Float parsing error

### ISSUE THREAD

**Issue by philss** [simd-lite/simd-json#251]
First of all, thank you for this library!

I'm reporting an issue found first here: https://github.com/pola-rs/polars/issues/5021

I found a float parsing error while trying to parse the number `0.6`. It returns the number `0.6000000000000001`, which suggests that the parser is not doing an approximation for that number (I don't understand that much of floats, so it's just a guess).

I tested parsing the same number with the original implementation of simd json, and it works.

I saw that a PR was made regarding this subject - https://github.com/simd-lite/simd-json/pull/127 -, and I would like to know if it's possible to have something like that under a feature. Thanks!

## Some test cases

```rust
// in the `src/lib.rs` file
#[test]
fn float3() {
    let mut d = String::from("0.6");
    let mut d = unsafe { d.as_bytes_mut() };
    let v_serde: serde_json::Number = serde_json::from_slice(d).expect("serde_json");
    let v_simd: serde_json::Number = from_slice(&mut d).expect("simd_json");
    assert_eq!(v_simd, v_serde);
}

#[test]
fn float4() {
    let mut d = String::from("-12345678901234.56789012");
    let mut d = unsafe { d.as_bytes_mut() };
    let v_serde: serde_json::Number = serde_json::from_slice(d).expect("serde_json");
    let v_simd: serde_json::Number = from_slice(&mut d).expect("simd_json");
    assert_eq!(v_simd, v_serde);
}
```

The results:

```
failures:

---- tests_serde::float4 stdout ----
thread 'tests_serde::float4' panicked at 'assertion failed: `(left == right)`
  left: `Number(-12345678901234.568)`,
 right: `Number(-12345678901234.566)`', src/lib.rs:1512:9

---- tests_serde::float3 stdout ----
thread 'tests_serde::float3' panicked at 'assertion failed: `(left == right)`
  left: `Number(0.6000000000000001)`,
 right: `Number(0.6)`', src/lib.rs:1503:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests_serde::float3
    tests_serde::float4

test result: FAILED. 243 passed; 2 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.75s
```

Tested against https://github.com/simd-lite/simd-json/commit/669e691f765e1345ef3ea3c55cad70384dd601da

**Comment by Licenser** [comment]
Heya, the PR was closed because the author disappeared, if you want to open a new one that's totally welcome, either behind a feature flag (either for fast or for correct) or as a general implementation if the perf isn't too much of a pain. the next release will not be backwards incompatible anyway so now is a perfect time :)

**Comment by philss** [comment]
Hi @Licenser :wave: I'm going to try bring his/her work back. I should run some benchmarks before creating the feature flag. I will let you know. Thanks!

**Comment by Licenser** [comment]
<3 huzza! If you need any help let me know :)
