### ISSUE TITLE
Unable to compile to `armv7-unknown-linux-gnueabihf` target

### ISSUE THREAD

**Issue by universalmind303** [simd-lite/simd-json#263]
it appears that `parse_eight_digits_unrolled` is not available on this target, even when `allow-nonsimd` feature is enabled
```
Error:  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.7.0/src/numberparse/correct.rs:7:43
  |
7 | use super::{is_made_of_eight_digits_fast, parse_eight_digits_unrolled};
  |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `parse_eight_digits_unrolled` in `numberparse`
```

**Comment by Licenser** [comment]
Heya, the function requires the features:

**architecture:** `neon`
and the target 

**target_feature:**  `simd128`

can you look at the features available on your platform?

**Comment by hustcer** [comment]
Same here: https://github.com/hustcer/nu-release/actions/runs/5206601207/jobs/9393333135

**Comment by Licenser** [comment]
closing this since there hasn't been a reply from the author for nearly 9 month
