### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by tarasbogach** [simd-lite/simd-json#277]
```
Compiling simd-json v0.8.0
error[E0308]: mismatched types
   --> /home/tl/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.8.0/src/lib.rs:228:86
    |
228 | fn please_compile_with_a_simd_compatible_cpu_setting_read_the_simdjsonrs_readme() -> ! {}
    |    ----------------------------------------------------------------------------      ^ expected `!`, found `()`
    |    |
    |    implicitly returns `()` as its body has no tail or `return` expression
    |
    = note:   expected type `!`
            found unit type `()`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `simd-json` due to previous error
```

**Comment by Licenser** [comment]
https://github.com/simd-lite/simd-json#cpu-target

**Comment by tarasbogach** [comment]
cat /proc/cpuinfo  | grep avx

flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 *sse4_2* x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 *avx2* smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

**Comment by tarasbogach** [comment]
Sorry for the inconvenience. You can close this one.

**Comment by Licenser** [comment]
No worries, all good, just really hard to help this way :)
