### ISSUE TITLE
Docs: add table to readme containing all tested architectures.

### ISSUE THREAD

**Issue by universalmind303** [simd-lite/simd-json#278]
A lot of targets don't seem to compile with `simd_json`. To avoid confusion, it'd be nice to have a table on the front page containing all compile targets that are confirmed to work.

**Comment by Licenser** [comment]
I don't think that it makes a lot of sense, where simd-json works has more to do with CPU architecture then rust targets

**Comment by universalmind303** [comment]
sorry, that's more along the lines of what i meant. tested cpu architectures, not tested rust targets. I updated title accordingly.

**Comment by Licenser** [comment]
Oh, yes, that witht the link explains nicely what you're looking for, that makes sense I thought you are asking for a 10000 entry table with every rust target or every CPU ever released ;) I'll add this and fill it out as good as possible. Most of it will be copy&paste from upstream as it's for the most part the same algorithm

**Comment by Licenser** [comment]
While not a table the readme now calls out supported architectures in multiple places that should be enough for a user to figure out where they stand
