### ISSUE TITLE
Discover cpu features at runtime

### ISSUE THREAD

**Issue by ozgrakkurt** [simd-lite/simd-json#285]
Hey!

Why not do this in runtime to support portable binaries? A lot of things run on cloud which makes target-cpu=native not very good in a lot of situations

**Comment by Licenser** [comment]
There is an issue for this already, it's less about want then having time for it https://github.com/simd-lite/simd-json/issues/104

**Comment by ozgrakkurt** [comment]
@Licenser thanks! sorry for extra issue

**Comment by Licenser** [comment]
All good :)
