### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by NikZak** [simd-lite/simd-json#286]
I'm very interested in incorporating simd_json into my project. However I am not sure how to solve a few problems:
1) I need to parse json up to a certain value (timestamp) and if timestamp is below a given timestamp, I don't need to parse further. Just stop and return. In serde I use DeserializeSeed as stateful deserializer with timestamp in the state and implement my own visit_map and use IgnoredAny after the predicate is met
2) I would like to parse a sequence of tuples of floats but only first 10 values. (In serde I would use IgnoredAny again after the 10th value or abort)
3) Optional: I would like to minimize allocations and ideally parse into a given external buffer (target structure with preallocated vec). In serde I can use DeserializeSeed for a stateful deserializer and provide a buffer to it. Maybe this is not needed as snmalloc is highly optimized allocator already. 

Could you give some hints or point to a direction how to use simd-json with these problems?

**Comment by Licenser** [comment]
The parsing process is done in steps in simd-json, the best starting point would be to use tape representation and stop consuming it once you hit a stop point. If that's not performant enough an alternative but a much more complicated, one that would loose the benefit it being a validating parser, is to consume the stage one result which basically just point to the start of structural elements. It would work well enough if you need a specific structure to be parsed really fast but would be a bit of extra work and might require exposing some internal functions. 

On the buffer part there is a parse function that takes pre-allocated buffers already:) that should do the trick I hope ;)

**Comment by NikZak** [comment]
Thank you! I'm still reading the code. But is it correct to say that if I use .to_tape() and get the Tape struct that consists of Vec<Node> then it means that the bytes have been already parsed. Otherwise how would it know how many Nodes are there and what kind of objects are they. So seems that some additional work is already done, although I could have stopped parsing after the first element if timestamp is old.

**Comment by Licenser** [comment]
Heya, yes, that's the algorithm's nature, it is a multi-pass parser, so it will go over the entire memory more then once. While this sounds wasteful, it is actually pretty fast as each pass is optimized and significantly faster then single-pass parsing, even when added up.

The passes are:

1) analyze the structure (find the offsets of structural bytes)
2) parse data (turn characters into number unescape strings etc)
3) turn it into a data structure

The `to_tape` gives the result of the second pass, a tape of pointers (references) and stack-allocated variables, no allocations are done for nested structures but a validation of the data (all arrays and objects start and end in correct order, keys are strings, strings and numbers are valid etc.)

That'd by my first try to hook into.

The alternative is to hook into the process after the first, but you wold not get the benefit of a validating parser any more

**Comment by jcuenod** [comment]
@NikZak Maybe I'm wrong here, but you might look at squirrel https://github.com/datalust/squirrel-json.

> ... If only a fraction of that document is actually needed to satisfy a given query then only that fraction will pay the cost of full deserialization.

**Comment by Licenser** [comment]
I think this can be closed by now, feel free to re-open if requried
