### ISSUE TITLE
What is the equivalent of `raw_value` feature from serde_json?

### ISSUE THREAD

**Issue by utkarshgupta137** [simd-lite/simd-json#298]
We want access to the exact (f64) string that was present in the input. We have our own mechanism for parsing decimals from strings & internally representing them in our application. So we'd like access to the original string from the input instead of getting an f64. Ideally, simd-json should be able to use `RawValue` from serde_json, but since that doesn't work, I was wondering if simd-json could provide an alternative (or fix compatibility with `RawValue`).

The following code works with serde_json, but not simd-json:

```rust
use serde::{Deserialize, Deserializer};
use serde_json::value::RawValue;

#[derive(Debug, Deserialize)]
pub struct Struct {
    #[serde(deserialize_with = "deserialize")]
    pub field1: f64,
    #[serde(deserialize_with = "deserialize")]
    pub field2: f64,
    #[serde(deserialize_with = "deserialize")]
    pub field3: f64,
}

fn deserialize<'de, D>(deserializer: D) -> Result<f64, D::Error>
where
    D: Deserializer<'de>,
{
    let v: &RawValue = Deserialize::deserialize(deserializer)?;

    Ok(my_special_parser(v.get()))
}

fn my_special_parser(s: &str) -> f64 {
    s.parse().unwrap()
}

fn main() {
    let mut s = r#"{"field1": 1.0, "field2": 2.0, "field3": 3.0}"#.to_string().into_bytes();
    println!("{:?}", serde_json::from_slice::<Struct>(&s).unwrap());
    println!("{:?}", simd_json::from_slice::<Struct>(&mut s).unwrap()); // <----- Errors
}
```

**Comment by utkarshgupta137** [comment]
So I dug into the source code a bit & it looks like simd-json first deserializes into an internal structure, then it passes those values to serde's `Deserializer` trait. So it is always f64 when deserializing which is why I can't get a `RawValue` from it, as it is already deserialized to f64. AFAICT, to support something like `RawValue` might require a few changes, i.e. how do I tell `simd-json` which fields I want as `RawValue` & which I don't. The other option might be to not do the whole conversion into the internal structure first - but that might defeat some performance gains I guess?

For my use case, #297 seems to be better suited & easier to implement.

What do the maintainers think? Feel free to close this if you think this can't be done without performance penalties.

**Comment by Licenser** [comment]
The best way to achive something equivalent would be accessing the stage 1 tape to construct your data, I'm not sure it's a public interface but if not it might be worth exposing it (perhaps behind a feature flag).

the statge-1 tape is the offsets of the data that could be consumed "as is" without simd-json doing any type checking / any string rewriting etc.

**Comment by utkarshgupta137** [comment]
> The best way to achive something equivalent would be accessing the stage 1 tape to construct your data, I'm not sure it's a public interface but if not it might be worth exposing it (perhaps behind a feature flag).
> 
> the statge-1 tape is the offsets of the data that could be consumed "as is" without simd-json doing any type checking / any string rewriting etc.

That would be a little too difficult for us to add & maintain. We want something that is still compatible with serde & serde_json. From my peek at the source code, #297 should be doable & provide us exactly what we're looking for.

I'm closing this, but feel free to reopen.
