### ISSUE TITLE
Security advisory for lexical?

### ISSUE THREAD

**Issue by jqnatividad** [simd-lite/simd-json#312]
https://github.com/advisories/GHSA-c2hm-mjxv-89r4
https://rustsec.org/advisories/RUSTSEC-2023-0055.html

sims-json is using `lexical-core` which seems to be an an affiliated crate to lexical.

Might be worthwhile to investigate.

**Comment by jeadorf** [comment]
Yes, the lexical dependency prevents a use case of simd-json I'm interested in.

`simd-json` depends on `lexical-core` in only one place, apparently: [simd-json/src/numberspace/correct.rs](https://github.com/simd-lite/simd-json/blob/19ddf6c475c5befc4fdcf416737256a60a93b899/src/numberparse/correct.rs#L384).

```rs
#[cold]
fn f64_from_parts_slow(slice: &[u8], offset: usize) -> Result<StaticNode> {
    match lexical_core::parse_with_options::<f64, { lexical_core::format::JSON }>(
        slice,
        &lexical_core::parse_float_options::JSON,
    ) {
        Ok(val) => {
            if val.is_infinite() {
                err!(offset, get!(slice, 0))
            }

            Ok(StaticNode::F64(val))
        }
        Err(_) => err!(offset, get!(slice, offset)),
    }
}
```

**Is this function tested?** I could not find any tests. It is also marked with the cold attribute (https://doc.rust-lang.org/reference/attributes/codegen.html#the-cold-attribute), suggesting that it's unlikely to be called.

https://rustsec.org/advisories/RUSTSEC-2023-0055.html

> For quickly parsing floating-point numbers third-party crates are no longer needed. A fast float parsing algorithm by the author of lexical has been merged into libcore.

It seems that this can be fixed on the simd-json side, using some standard library functionality, and the dependency on lexical removed entirely.

**Comment by Licenser** [comment]
It's noteworthy that the RUSTSEC advisory is for `lexical`, not `lexical-core`, so either the advisory was filed incorrectly, or it isn't related. 

That said, I looked up the difference in format and it seems to be only about nan/inf strings which don't exist in JSON, I guess we can ignore that difference and use the standard methods.

So I'm happy to merge a PR if someone wants to open one or do it myself when time permits

**Comment by Licenser** [comment]
released as 0.14.0-rc.2

**Comment by Alexhuszagh** [comment]
I was looking at crates that might have missed the security advisory for lexical-core and I just wanted to confirm that this did affect lexical-core (RUSTSEC-2023-0086), and any recent version of the Rust standard library should provide amenable performance except in extenuating circumstances (floats with large numbers of digits very close to half-way rounding), so removal is almost certainly the best option here.

**Comment by Licenser** [comment]
Hi @Alexhuszagh thanks for the context! I came to the same conclusion, the fix for this was removing the dependency all together - possible behavioral changes forced it into a increased version number but aside of that 👍
