### ISSUE TITLE
simd_json::OwnedValue and simd_json::BorrowedValue

### ISSUE THREAD

**Issue by PSeitz** [simd-lite/simd-json#324]
I think `simd_json::OwnedValue` can be removed and replaced with `simd_json::BorrowedValue` + A owning wrapper.
I've applied a similar technique here: https://github.com/PSeitz/serde_json_borrow/blob/main/src/owned.rs

It would also remove some `unsafe`, since we can use `into_bytes()`.

As it is now, with the mutable slice as parameter, ownership is given up anyways, as the inplace de-escaping (which is awesome by the way) garbles the input a little bit.

I've also seen that `BorrowedValue` contains `String(Cow<'value, str>)`, but isn't the `Cow` unnecessary since the Strings are already escaped?

**Comment by Licenser** [comment]
Getting rid of the Cow and (or) replacing OwnedValue with a wrapper would force both data structures to be immutable which will make them significantly less useful.

**Comment by PSeitz** [comment]
> Getting rid of the Cow and (or) replacing OwnedValue with a wrapper would force both data structures to be immutable which will make them significantly less useful.

I agree on `Cow` removing mutability. BorrowedValue is mutable, why would replacing OwnedValue with BorrowedValue + a owning wrapper remove mutability?

**Comment by Licenser** [comment]
I've created simplified example on the playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c6d61dd3a62de4cb4c9a87bdfae827a3

**Comment by PSeitz** [comment]
It compiles with explicit lifetimes:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f9b8fe8052b086f8eec7795dda00aa7a

Although I think the static part should be cast away, as it is just a hack and not the real lifetime.

```rust
pub fn get_value_mut<'a>(&'a mut self) -> &'a mut Vec<Cow<'a, str>> {
    unsafe{std::mem::transmute::<&mut Vec<Cow<'static, str>>, &mut Vec<Cow<'a, str>>>(&mut self.value)}
}
```

**Comment by Licenser** [comment]
This introduces [unsoundness problems](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=612956403e59b0c0da5e1d69e80b5bc4). There are probably ways around it but given it is not clear to the user I'd rather avoid the risk especially if the benefit is just a bit less code in the upstream library. It'd not be a significant improvement but a serious risk of getting something wrong.

**Comment by PSeitz** [comment]
The static is just an internal hack for the self reference, it should not be exposed to the user. The real lifetime is bound to self. With that I don't think it can be misused: 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4497772497dee362fac8f2c5edf45314

**Comment by Licenser** [comment]
The reason why I'm so much against this is that while it looks right, it's so easy to  get it wrong, the code still can be broken:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=de21049da8984c8d7f43a12b74d5294f

Transmuting lifetimes around is extremely risky. The code works without having that risk at a meager cost of a bit of extra code to maintain. I prefer "boring code" that works over elegant code that might explode.
