### ISSUE TITLE
Raw JSON values

### ISSUE THREAD

**Issue by monoid** [simd-lite/simd-json#325]
`serde_json` has [`RawValue`](https://docs.rs/serde_json/latest/serde_json/value/struct.RawValue.html) types that works like a slice pointing to a valid subdocument withing the orignal JSON data.

It has at least two applications:
1. On deserializing, particular parts of document are then serialized as-is.  It saves on allocations and copying.
2. Sometime all one needs is check that document is a valid JSON. Then trying to deserialize it to `RawValue` is very effective (again, much less allocations).

`serde_json` has a special kludge to parse and store `RawValues`, using it directly with `simd_json` doesn't work.

**Comment by monoid** [comment]
Thanks! Right now p. 2 is the most important for me, will try to do it with a tape!

**Comment by Licenser** [comment]
https://docs.rs/simd-json/latest/simd_json/fn.to_tape.html is what you want for that :)

**Comment by Licenser** [comment]
I'll close this issue since it is mostly answered and the rest is more correctly captured in #82

**Comment by monoid** [comment]
Yes, thanks!
