### ISSUE TITLE
Missing Contribution.md

### ISSUE THREAD

**Issue by Parth4git** [simd-lite/simd-json#344]
Problem or desire
The repository looks incomplete because of the missing CONTRIBUTING.md file to specify the rules and regulations to follow while contributing to any issue, bug, or new feature to the repository, I want to add that file to the repo. 

Proposal
Add the CONTRIBUTING file to the repository with guidelines.

Kindly assign me this issue. @Licenser

**Comment by Licenser** [comment]
You've an excellent point. Sorry that I overlooked adding a CONTRIBUTING.md 👍
