### ISSUE TITLE
wasm32-wasi doesn't seems to work

### ISSUE THREAD

**Issue by sehz** [simd-lite/simd-json#373]
Hi,  I am having trouble running on `wasm32-wasi` target.   It's 10x slower compared with native (Apple silicon) and 3x slower compared with running `serde-json` on wasm.   What feature should I enable to run properly?   I am using latest version of wasmtime.  

Thanks

**Comment by Licenser** [comment]
Hi,

I don't have much experience with wasm runtimes but it seems that is a 32 bit runtime while simd-json is optimized for 64bit and SIMD instructions and since it relies a lot on math I suspect it will suffer when the architecture is 32 bit and each calculation will need two or more instructions.

Also can you verify that the runtime actually uses native SIMD instructions and not just emulates them?

**Comment by sehz** [comment]
That make sense.  I can try verify the byte code to see if generated code uses WASM SIMD instruction set

**Comment by Licenser** [comment]
Even if it generates WASM SIMD instructions the wasm-runtime is still free to emulate them instead of using natives, I don't know how to validate it for `wasm32-wasi`

**Comment by sehz** [comment]
I see wasm tests are in here:  https://github.com/simd-lite/simd-json/blob/main/.github/workflows/tests.yml#L139

**Comment by sehz** [comment]
using 
```
simd-json = { version = "0.13.9", default-features = false, features = ["128bit","serde_impl", "swar-number-parsing"] }
```

Doesn't seem to generate any simd instruction from here: https://github.com/WebAssembly/simd/blob/master/proposals/simd/BinarySIMD.md

**Comment by Licenser** [comment]
You might need to set some flags for the rust compiler to tell it. that your target architecture supports them

**Comment by sehz** [comment]
Made to work.   I have to set RUSTC flag like here:
```
RUSTFLAGS='-C target-feature=+simd128' cargo build --target=wasm32-wasi --release
```

However, performance improvement was only 15%.  I suspect, need to use different allocator.   

Thanks for help.  Closing
