### ISSUE TITLE
Lift mutability requirement for `to_borrowed_value`/`to_owned_value` ?

### ISSUE THREAD

**Issue by equal-l2** [simd-lite/simd-json#380]
`simd-json`'s parsing functions requires the input buffer to be `&mut [u8]`, while `serde-json`'s equivalent (`serde_json::from_slice`) only requires `&[u8]`.
Is it possible to lift the mutability requirement, or is it inevitable for optimization in `simd-json` or any other reason?

**Comment by Licenser** [comment]
The reason for the mutability is that we perform in-situ parsing where possible. So strings that don't include escape sequences are never altered and just point to "the place in the buffer.", this is true for most strings in JSON documents (not all, mind you, and for some situations, not any); for strings with escape sequences, we re-use the input buffer to store the unescaped string and point to that.  We could avoid that at the cost of now having two buffers that hold lifetime dependencies on the input or by giving up on not copying strings without escape sequences, both seem to be a net negative. perhaps copying out all strings would be possible, on the other hand creating a clone of the input (if needed) is really cheap (it also happens in the parser itself to right size the input to simd-boundaries).

**Comment by equal-l2** [comment]
Thank you for the detailed explanation!
That makes sense to me,
