### ISSUE TITLE
Exposing return types of various iterators

### ISSUE THREAD

**Issue by abizjak** [simd-lite/simd-json#406]
A number of types for the lazy API are not accessible even though the methods that return them are public, and useful.

For example `Object.keys` returns a [`Keys`](https://docs.rs/simd-json/latest/simd_json/value/lazy/enum.Object.html#method.keys) structure that implements `Iterator`

This does not seem to be publicly accessible. The type is defined in 
https://docs.rs/simd-json/latest/src/simd_json/value/lazy/object.rs.html#23

This module is under `lazy` which only [re-exports](https://docs.rs/simd-json/latest/src/simd_json/value/lazy.rs.html#35) the `Object` and `Array` types.

I find myself in need of storing these returned iterators but I cannot name them since they are not exported.

Is there a reason why these are not publicly available? I can think of one reason, namely that you do not want to expose the internal details, and they are enums. But that could be solved by having a newtype wrapper around the inner enum. I'm happy making a PR doing this, but want to make sure it's not against the vision of the project.

**Comment by Licenser** [comment]
Heya,

sorry for the plate reply, I am vacationing :) so I wasn't watching the computer closely. Good catch; there was no reason other than me forgetting, and no one needs it now. I'll make the object and array modules so it's possible to get to the structs.

**Comment by Licenser** [comment]
Published as v0.14.3
