### ISSUE TITLE
Improved number handling

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simd-json#59]
It would be nice to improve number handling, right now we only have I64 and F64, this ignores U64 and extended values such as i and u 128.

defaulting to the 128 bit types will probably have a decreased performance we might want to avoid that, we could however extend then as additional types? but that would explode the number of types we have (however ValueTrait mittigates that).

we definetly want a u64 type along with the i64 one to be able to represent those numbers.

**Comment by sunnygleason** [comment]
I think there are some interesting things happening upstream for float processing as well:

https://github.com/lemire/simdjson/pull/303

**Comment by mstump** [comment]
Doesn't this just require modification [to this bit of code](https://github.com/simd-lite/simdjson-rs/blob/0deaa233cb8dfa5ee04bf2f62af309d9e49acfcf/src/numberparse.rs#L356)? I just ran into this issue parsing documents generated by ElasticSearch where it will emit statistics that contain a Java long.

```json
{
  "name": "max_unsafe_auto_id_timestamp",
  "value": -9223372036854776000
}
```

**Comment by Licenser** [comment]
-9_223_372_036_854_775_808 is the minimum signed 64 bit integer. The same value counts for [java long](https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html#MIN_VALUE). 
-9 223 372 036 854 776 000 is outside of this range and seems a very odd number I wonder why the maximum number is negative but I might miss context here. I would be curious where this number comes from. 

That said 128 bit integers have further implications then just that check as data types need to be changed which likely changes the memory layout (to be verified) and performance profile but we hope to get it as a future flag at least.

**Comment by Licenser** [comment]
so to verify, this isn't a bug in the parsing as a i64, that said I think we should fall back and treat that as a float (as much as it pains me) unless 128bit numbers are enabled.

![image](https://user-images.githubusercontent.com/119093/70165961-1cc07f00-16c4-11ea-8c0c-c34b9ed829dd.png)

Thoughts on that?

**Comment by mstump** [comment]
That works for me. It's not ideal but you're less likely to have things blow up unexpectedly.

**Comment by Licenser** [comment]
It will be important if we ever encounter something >128 bit. I’m still curious however why logstash sends a non 64 but number

**Comment by Licenser** [comment]
@sunnygleason just shared this: https://twitter.com/lemire/status/1200539056809091074 it seems to indeed be a floating point bug in ES, if you encounter this you should probably open a ticket with them. 

This doesn’t mean we shouldn’t handle it gracefully on our end.

**Comment by Licenser** [comment]
There seem to be some related issues reported https://github.com/elastic/elasticsearch/issues/28806 for example.
You can find more when looking for `9223372036854776000` is there something between Elastic and where you get the JSON from? Some kind of middleware, proxy or other system that processes the JSON?

**Comment by mstump** [comment]
In this instance we're scraping the management endpoints of ES ,consolidate them to a single doc and then forward on. What you're seeing is the raw value from ES. We're doing it for a variety of versions, some of which are ancient. I'll try the patch today or this weekend. For context serde-json is converting it to a float.

**Comment by Licenser** [comment]
Ja, there are pro’s and cons to that behavior, I personally prefer just having 128bit numbers (which turned out to be a lot easier then expected) so I think that’s the better approach

**Comment by Licenser** [comment]
I think support for 128 bit solves this
