### ISSUE TITLE
`Value` for Tape

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simd-json#82]
It would be nice to be able to use the tape with the functions that are provided or the `Value`-trait, for read only situations this might significantly faster. The current problem is around ownership (hello rust ...)

**Comment by CJP10** [comment]
@Licenser I wouldn't mind giving this a shot. Is the basic idea to do something like
```
impl Value for Tape {
    type Key = String;
    type Array = Vec<Tape>;
    type Object = HashMap<String, Tape>;
    // ...
}
```

**Comment by Licenser** [comment]
Give it a shot! I tried a few times and it came with some issues like .as_array() either having to create a new vector or doing other sneaky things and as_object just being genuenly scary w/o creating new data when accessing it but perhaps you find a nice way around those  :D

**Comment by CJP10** [comment]
Sounds like a challenge :smile:. Do you have the previous attempts somewhere?

**Comment by CJP10** [comment]
@Licenser looking through the value module there are tons of duplicated tests. It seems `borrowed.rs`, `owned.rs` and `tape.rs` have a lot of the same tests. Might make sense to bubble all of them up to `value.rs`.

**Comment by CJP10** [comment]
I also found that a `Node::Static(StaticNode::Null)` is inserted at position 0 of every tape. Any particular reason to do so?

**Comment by Licenser** [comment]
So the tests are not technically duplicated, they're the same tests run against different data representations. macro'ing them out might be an option? I think the alternative is to use one huge test that gets traited but then we don't get nice failures for cases anymore. A lot of them look trivial but they're good to catch simple errors (and have so in the past o.O) that can slip by easily.

As to the null that has to do with how upstream treated it, it alwys had a "root" node for a tape, it could probably be stripped (but doesn't do much harm I guess).

**Comment by CJP10** [comment]
There is a cost when "sub-taping" (representing a tape as a sub-slice of another). The root tape starts at index 1 where as other "sub-tapes" would start at 0 (they have no root node). Unfortunately, the `Value` trait is defined to return a reference, which makes passing additional metadata harder.

**Comment by CJP10** [comment]
@Licenser This is the definition I'm currently working.
```rust
pub struct Tape<'input>(Cow<'input, [Node]>);

impl<'input> Value for Tape<'input> {
    type Key = String;
    type Array = Tape<'input>;
    type Object = Tape<'input>;
    // ...
}
```

**Comment by CJP10** [comment]
@Licenser just a friendly ping 😃. I want to get to this during the weekend so if you have time your thoughts would be awesome.

**Comment by Licenser** [comment]
Sorry :) no worried about the ping, if I don't respond it's usually because my brain saw a squirrel somewhere (or actually a raven) and got distracted by other things 😂  so ping away whenever I drop the ball 👍 

The idea to wrap the tape ina  cow for this is neat, I didn't think of that 👍 lets see how that goes :D I'm excited!

**Comment by CJP10** [comment]
@Licenser are you ok with changing the value trait?

**Comment by Licenser** [comment]
That'd depend on the change and the pro/con on that. What do you have in mind?

**Comment by CJP10** [comment]
```rust
    fn as_array(&self) -> Option<&Self::Array>;
    fn as_object(&self) -> Option<&Self::Object>;
    
    // becomes

    // no longer returns ref
    fn as_array(&self) -> Option<Self::Array>;
    fn as_object(&self) -> Option<Self::Object>;
    // or a new associated type is added
    fn as_array(&self) -> Option<Self::ArrayRef>;
    fn as_object(&self) -> Option<Self::ObjectRef>;
```

**Comment by Licenser** [comment]
As no ref could cause some issues, with it breaking the contract that 'as_' is a no/low cost operation (i.e. no cloning or  allocaitons) returning a Array would make it extremely for most things. The second issue with that I see is that as_*_mut would then differ on signature which also isn't ideal.

Adding a ArrayRef associated type otoh I can't see many issues with. It would require updating the implemtations for the other Value* functions but it would be a non-change for most users so that could work think.

**Comment by CJP10** [comment]
Actually after looking a bit harder at this, both are equivalent. `Self::Array` and `Self::Object` are only used in the `as_*` functions so really it's just a naming difference between what I purposed.

**Comment by Licenser** [comment]
I think in the past I ran into an issue trying that, but I could just misremember :D or missed some easy solutions to the isuses (I'm pretty sure they were around lifetimes). If it works w/o slowing down other implementations of the value trait or change the canonical meaning I don't mind a change :).

On a (very late) feedback to earlier, I got no issue of removing the root node from the tape if that makes things eaiser (and doesn't break stuff :P)

**Comment by CJP10** [comment]
I'll give it a go and report back :)

**Comment by Licenser** [comment]
This is implemented
