### ISSUE TITLE
Split out code into many crates.

### ISSUE THREAD

**Issue by tkaitchuck** [simd-lite/simd-json#93]
Right now the crate provides a great way to parse json. But a lot of the simd tricks are much more general. For example parsing a float or an integer from a string, locating unescaped quotes, etc. may be valuable generally.

If these could be made into sub-crates that are individually pushed to crates.io they could be more easily reused in other contexts. 

If they can be made nostd perhaps simd parsing of ints/floats could even be added to the standard library instead of the `.parse()` method on string.

**Comment by Licenser** [comment]
That's a great idea!

**Comment by Licenser** [comment]
Not done but the relevant traits now live in `value-trait`

**Comment by Licenser** [comment]
we have split things out to the point where it makes sense now
