### ISSUE TITLE
Investigate 'faster-utf8-validator' for utf8 validation

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simd-json#98]
We should look at https://github.com/zwegner/faster-utf8-validator and see if porting it would improve parsing performance

**Comment by sunnygleason** [comment]
Interesting. Is this present in upstream and/or can we get it there? I'm a little wary of deviating, especially since we have work to do to get closer to the latest simdjson release series. (Work to resemble the templating and runtime ability)

**Comment by Licenser** [comment]
That's a valid point and I honestly don't know. I think it'd depend on if it's worth it, before knowing if / what impact it has it's hard to say one way or the other. But I would think that if it has a positive performance impact it's likely that upstream would accept it.

**Comment by Licenser** [comment]
I ported the utf8 validator to rust: https://github.com/simd-lite/faster-utf8-validator-rs

**Comment by CJP10** [comment]
Looks like upstream now uses https://github.com/simdjson/simdjson/blob/master/src/generic/stage1/utf8_lookup4_algorithm.h. @Licenser I'm working on a port similar to https://github.com/simd-lite/faster-utf8-validator-rs, once I'm finished maybe we offer both under feature flags?

**Comment by Licenser** [comment]
Absolutely, thank you!

The reason we didn't adopt something like faster-utf8 yet is that the current validator ties in nicely with the algorithm (so will the new one in simdjson) both take advantage of using the same registers for multiple things but I think that shouldn't be an issue with a port of lookup4 :D
